import { Helmet } from "react-helmet-async";
import { AboutBanner } from "../components/About/AboutBanner";
import { AboutContent } from "../components/About/AboutContent";
import { OurTechnologyAbout } from "../components/OurTechnology/OurTechnologyAbout";
import { TechnologyImgBox } from "../components/OurTechnology/TechnologyImgBox";
import OurTechnologyimg from "./../assets/images/outtechnologyimg.jpeg";

export const OurTechnology = () => {
  return (
    <div>
      <AboutBanner
        bannerTitle="Our Technology"
        bannerDesc="A Joyful Journey of Mindful Beauty and Imagination"
      />
 <Helmet>
        <script>
          {`
            (function (c, s, q, u, a, r, e) {
              c.hj = c.hj || function () { (c.hj.q = c.hj.q || []).push(arguments) };
              c._hjSettings = { hjid: 6369861 };
              r = s.getElementsByTagName('head')[0];
              e = s.createElement('script');
              e.async = true;
              e.src = q + c._hjSettings.hjid + u;
              r.appendChild(e);
            })(window, document, 'https://static.hj.contentsquare.net/c/csq-', '.js', 6369861);
          `}
        </script>
      </Helmet>
      <OurTechnologyAbout />

      <div className="lg:py-[60px] py-[40px]">
        <div className="mb-6">
          <AboutContent
            title="AI and AR in Beauty"
            descriptions={[
              `At Mindful Beauty, we harness the power of Artificial Intelligence and Augmented Reality to revolutionize your beauty experience. Our AI algorithms provide predictive analysis, tailoring skincare and beauty routines to each individual’s unique needs. Augmented Reality brings a new dimension to your beauty journey, allowing for virtual try-ons that make choosing the perfect product or style effortless and fun.`,
            ]}
          />
        </div>
        <div className="mb-6">
          <AboutContent
            title="Platform Capabilities"
            descriptions={[
              "Our platform goes beyond the surface, offering real-time insights into skin health and product effectiveness. With personalized care plans generated by our AI, you’ll see a transformative approach to beauty that adapts and responds to your skin’s changing needs over time. It’s intuitive, interactive, and imbued with the expertise of leading beauty professionals.",
            ]}
          />
        </div>
      </div>
      <div className="pb-[40px]">
        <TechnologyImgBox bgImage={OurTechnologyimg} />
      </div>
    </div>
  );
};
